---
# yaml-language-server: $schema=https://blue-build.org
name: template
description: Bazzite with hard-baked MT7927 driver and blacklist
base-image: ghcr.io/ublue-os/bazzite-gnome-nvidia
image-version: latest

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: files
    files:
      - source: system
        destination: / # copies files/system/* (* means everything inside it) into your image's root folder /

  - type: rpm-ostree
    install:
      - dkms
      - kernel-devel
      - kernel-headers

  - type: dnf
    repos:
      copr:
        - atim/starship
    install:
      packages:
        - micro
        - starship
    remove:
      packages:
        # example: removing firefox (in favor of the flatpak)
        # "firefox" is the main package, "firefox-langpacks" is a dependency
        - firefox
        - firefox-langpacks # also remove firefox dependency (not required for all packages, this is a special case)

  - type: default-flatpaks
    configurations:
      - notify: true # Send notification after install/uninstall is finished (true/false)
        scope: system
        # If no repo information is specified, Flathub will be used by default
        install: # system flatpaks we want all users to have and not remove
          - org.mozilla.firefox
          - org.gnome.Loupe
      - scope: user # Also add Flathub user repo, but no user packages

  - type: containerfile
    snippets:
      # 1. Firmware kopieren
      - COPY firmware/* /usr/lib/firmware/mediatek/mt7927/
      # 2. Den falschen Treiber blacklisten
      - RUN printf "blacklist mt7925e\ninstall mt7925e /bin/false\n" > /etc/modprobe.d/blacklist-mt7925e.conf
      # 3. Das Repository direkt erstellen (kein curl nötig)
      - |
        RUN printf "[copr:copr.fedorainfracloud.org:jetm:mediatek-mt7927-dkms]\n\
        name=Copr repo for mediatek-mt7927-dkms owned by jetm\n\
        baseurl=https://fedorainfracloud.org\$basearch/\n\
        type=rpm-md\n\
        skip_if_unavailable=True\n\
        gpgcheck=1\n\
        gpgkey=https://fedorainfracloud.org\n\
        repo_gpgcheck=0\n\
        enabled=1\n\
        enabled_metadata=1\n" > /etc/yum.repos.d/_copr_jetm-mediatek-mt7927.repo
      # 4. Den Treiber fest installieren
      - RUN rpm-ostree install mediatek-mt7927-dkms
      
  - type: signing # this sets up the proper policy & signing files for signed images to work fully
